name: Prisma DB Push

on:
  push:
    branches: [ main ]

jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Prisma DB Push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma db push --accept-data-loss
